//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.AssetDisposals = new HashSet<AssetDisposals>();
            this.AssetMovements = new HashSet<AssetMovements>();
            this.Maintenance = new HashSet<Maintenance>();
        }
    
        public int AssetID { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public int StatusID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> ResponsibleEmployeeID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDisposals> AssetDisposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetMovements> AssetMovements { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual AssetStatuses AssetStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
    }
}
