//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDisposals
    {
        public int DisposalID { get; set; }
        public int AssetID { get; set; }
        public System.DateTime DisposalDate { get; set; }
        public string DisposalReason { get; set; }
        public int ApprovedByUserID { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Assets Assets { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
