//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMovements
    {
        public int MovementID { get; set; }
        public int AssetID { get; set; }
        public int FromLocationID { get; set; }
        public int ToLocationID { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string Reason { get; set; }
        public int CreatedByUserID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Users Users { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Locations Locations1 { get; set; }
    }
}
