//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardStats
    {
        public int StatsID { get; set; }
        public Nullable<int> TotalAssets { get; set; }
        public Nullable<int> ActiveAssets { get; set; }
        public Nullable<int> InStorageAssets { get; set; }
        public Nullable<int> InRepairAssets { get; set; }
        public Nullable<int> DisposedAssets { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> MovementsThisMonth { get; set; }
        public Nullable<int> MaintenanceThisMonth { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
