//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AssetsByDepartment
    {
        public string DepartmentName { get; set; }
        public Nullable<int> AssetCount { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    }
}
