//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AssetsFullInfo
    {
        public int AssetID { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string Description { get; set; }
        public string CategoryName { get; set; }
        public string ManufacturerName { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string StatusName { get; set; }
        public string StatusColor { get; set; }
        public string LocationName { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ResponsibleEmail { get; set; }
        public string ResponsibleDepartment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
