//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MovementHistory
    {
        public int MovementID { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string Reason { get; set; }
        public string MovedBy { get; set; }
    }
}
