//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UsersInfo
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public Nullable<bool> UserIsActive { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string RoleName { get; set; }
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string PositionName { get; set; }
        public string DepartmentName { get; set; }
    }
}
